# worldSocketX
# Version: ${project.version}
# Gitgub: https://github.com/mc-serverworld/worldSocketX

configinfo:
  api-version: 1
  debug: false

general:
  port: 18964
  #port of socket

socketserver:
  threads: 100
  #Number of client

client:
  uuid: ""
  #dont touch UUID
  host: "127.0.0.1"
  check-rate: 60
  #rate to check connection, use tick (20tick = 1sec)

SSL:
  keyStore_file: "D:\\certificates\\minecraft\\KeyStore.keystore"
  trustStore_file: "D:\\certificates\\minecraft\\TrustStore.keystore"
  keyStorePassword: "changeit"
  trustStorePassword: "changeit"