name: JAVA CI Main
on:
  push:
    branches: [ main ]
jobs:
  openJDK_17:
    runs-on: [ MISF-SERVER-1-GithubRunner-1 ]
    steps:
      - name: Base setup
        uses: actions/checkout@v2
        with:
          clean: false

      - name: Set up openJDK 17 win64
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: 'jdkfile'
          jdkFile: "C:/java/jdk-17/openjdk-17_windows-x64_bin.zip"

      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v18
        with:
          servers: '[{ "id": "releases", "username": "${{ secrets.NEXUS_USERNAME}}", "password": "${{ secrets.NEXUS_PASSWORD}}" }, { "id": "snapshots", "username": "${{ secrets.NEXUS_USERNAME}}", "password": "${{ secrets.NEXUS_PASSWORD}}" }]'

      - name: Maven deploy
        run: |
          mvn deploy -T9000 -DskipTests