name: worldMISF JAVA CI Main
on:
  push:
    branches: [ main ]
jobs:
  openJDK_16_0_1:
    runs-on: [MISF-SERVER-1-GithubRunner-1]
    steps:
      - name: Base setup
        uses: actions/checkout@v2
        with:
          clean: false

      - name: Set up openJDK 16.0.1 win64
        uses: actions/setup-java@v1
        with:
          java-version: "16.0.1"
          jdkFile: "G:/BuildUtils/Jdk/openJdk/openjdk-16.0.1_windows-x64_bin.zip"

      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v18
        with:
          servers: '[{ "id": "releases", "username": "${{ secrets.NEXUS_USERNAME}}", "password": "${{ secrets.NEXUS_PASSWORD}}" }, { "id": "snapshots", "username": "${{ secrets.NEXUS_USERNAME}}", "password": "${{ secrets.NEXUS_PASSWORD}}" }]'

      - name: Maven deploy
        run: |
          mvn deploy -T9000 -DskipTests
