name: worldMISF JAVA CI Main
on:
  push:
    branches: [ main ]
jobs:
  serverworldRunner1_openJDK_16_0_1:
    runs-on: [MISF-SERVER-1-GithubRunner-2]
    steps:
      - uses: actions/checkout@v2
        with:
          clean: false
      - name: Set up openJDK 16.0.1 win64
        uses: actions/setup-java@v1
        with:
          java-version: "16.0.1"
          jdkFile: "G:/BuildUtils/Jdk/openJdk/openjdk-16.0.1_windows-x64_bin.zip"
      - name: Maven deploy
        run: |
          mvn deploy -T90000 -DskipTests
